name: Import Azure Resource into Terraform State

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Specifies the environment of the deployment."
        required: true
        type: choice
        default: "dev"
        options:
        - "dev"
      config:
        description: "Specifies the config of the deployment."
        required: true
        type: choice
        default: "dev"
        options:
        - "dev"
      import_target:
        required: true
        type: string
        description: 'Specifies the terraform resource address (e.g., azurerm_resource_group.my_rg)'
      resource_id:
        required: true
        type: string
        description: "Specifies the resource id to import (e.g., /subscriptions/.../resourceGroups/myResourceGroup)"

jobs:
  terraform_import:
    uses: ./.github/workflows/_terraformImportTemplate.yml
    name: "Import"
    with:
      environment: ${{ inputs.environment }}
      config: ${{ inputs.config }}
      terraform_version: "1.13.4"
      node_version: 24
      working_directory: "./code/infra"
      tenant_id: "37963dd4-f4e6-40f8-a7d6-24b97919e452"
      subscription_id: "1fdab118-1638-419a-8b12-06c9543714a0"
      import_target: ${{ inputs.import_target }}
      resource_id: ${{ inputs.resource_id }}
    secrets:
      CLIENT_ID: ${{ secrets.CLIENT_ID }}
